#!/usr/bin/env python3
"""Build a compact audit table for the full PyTorch-AD HBO/NBO runs.

The packaged HBO/NBO evidence is generated by ``run_hbo_full_experiments.py``
(or the compatibility entry point ``run_source_nbo_full_experiments.py``).  The
runner uses fully trainable actor/critic MLPs, PyTorch automatic differentiation
for value time gradients, value gradients, exact state Hessians, and actor
Hamiltonian gradients, plus terminal boundary loss and held-out rollout
evaluation.  This script is a lightweight tabulator; it does not retrain the
networks.
"""
from __future__ import annotations

import csv
import json
import math
import statistics as stats
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'data'


def read_csv(name: str) -> list[dict[str, str]]:
    with (DATA / name).open(newline='') as fh:
        return list(csv.DictReader(fh))


def row_for(rows: list[dict[str, str]], experiment: str, method: str) -> dict[str, str]:
    for row in rows:
        if row.get('experiment') == experiment and row.get('method') == method:
            return row
    raise KeyError((experiment, method))


def paired_gap(seed_rows: list[dict[str, str]], experiment: str, method_a: str, method_b: str, metric: str) -> tuple[float, float]:
    a = {r['seed']: float(r[metric]) for r in seed_rows if r['experiment'] == experiment and r['method'] == method_a and r.get(metric, '') != ''}
    b = {r['seed']: float(r[metric]) for r in seed_rows if r['experiment'] == experiment and r['method'] == method_b and r.get(metric, '') != ''}
    keys = sorted(set(a) & set(b), key=int)
    diffs = [a[k] - b[k] for k in keys]
    mean = sum(diffs) / len(diffs)
    ci = 1.96 * stats.stdev(diffs) / math.sqrt(len(diffs)) if len(diffs) > 1 else 0.0
    return mean, ci


def final_diag(diags: list[dict[str, str]], experiment: str, method: str) -> dict[str, str]:
    rows = [r for r in diags if r['experiment'] == experiment and r['method'] == method]
    if not rows:
        raise KeyError((experiment, method))
    return max(rows, key=lambda r: int(r['iteration']))


def main() -> int:
    metrics = read_csv('source_nbo_metrics.csv')
    seeds = read_csv('source_nbo_seed_metrics.csv')
    diags = read_csv('source_nbo_training_diagnostics.csv')
    meta = json.loads((DATA / 'source_nbo_run_metadata.json').read_text())
    specs = {
        'exp1_habit_portfolio': {
            'full': 'nbo_full_ndu',
            'comparator': 'nbo_fixed_pref',
            'metric': 'mean_utility',
            'status': 'hbo_ad_strict_gain',
            'read': 'The full PyTorch-AD HBO/NBO actor--critic run gives a held-out utility gain over the fixed-preference actor in the wealth-habit benchmark.',
        },
        'exp2_hidden_regime': {
            'full': 'nbo_full_ndu',
            'comparator': 'nbo_fixed_pref_recurrent',
            'metric': 'mean_utility',
            'status': 'hbo_ad_strict_small_gain',
            'read': 'The full PyTorch-AD HBO/NBO run gives a small positive held-out utility gain over the recurrent fixed-preference actor and the privileged-action diagnostic row.',
        },
        'exp3_high_dimensional_allocation': {
            'full': 'nbo_full_ndu',
            'comparator': 'nbo_fixed_pref_joint',
            'metric': 'mean_utility',
            'status': 'hbo_ad_feasible_parity_oracle_reference_higher',
            'read': 'The full PyTorch-AD HBO/NBO run is statistically tied with the feasible fixed-preference joint-action comparator; the privileged factor row remains higher because it uses hidden factor information not available to the feasible Full actor.',
        },
        'inventory_service_level': {
            'full': 'nbo_full_ndu_inventory',
            'comparator': 'nbo_action_only_inventory',
            'metric': 'mean_welfare',
            'status': 'hbo_ad_inventory_dominates_action_and_fixed_service',
            'read': 'The full PyTorch-AD HBO/NBO inventory actor improves the action-only inventory actor and the fixed-service base-stock reference on the corrected service-pressure welfare evaluator.',
        },
    }
    out = []
    for benchmark, cfg in specs.items():
        full = row_for(metrics, benchmark, cfg['full'])
        comp = row_for(metrics, benchmark, cfg['comparator'])
        gap, ci = paired_gap(seeds, benchmark, cfg['full'], cfg['comparator'], cfg['metric'])
        fd = final_diag(diags, benchmark, cfg['full'])
        cd = final_diag(diags, benchmark, cfg['comparator'])
        row = {
            'benchmark': benchmark,
            'solver': meta['algorithm'],
            'algorithm_source': 'Neural_Bellman_Operators.zip: fully trainable actor and value networks trained with L_PERF + omega L_HJB, terminal boundary loss, and PyTorch AD value gradients/Hessians plus actor Hamiltonian gradients',
            'full_method': cfg['full'],
            'comparator_method': cfg['comparator'],
            'primary_metric': cfg['metric'],
            'full_value': full[cfg['metric']],
            'comparator_value': comp[cfg['metric']],
            'full_minus_comparator_paired': f'{gap:.12g}',
            'paired_ci95': f'{ci:.12g}',
            'seed_count': full['seed_count'],
            'train_steps': str(meta['train_steps']),
            'width': str(meta['width']),
            'batch': str(meta['batch']),
            'omega': str(meta['omega']),
            'actor_lr': str(meta['actor_lr']),
            'critic_lr': str(meta['critic_lr']),
            'automatic_differentiation': str(meta.get('automatic_differentiation', 'PyTorch AD')),
            'initialization': str(meta.get('initialization', 'safe_constant_bias_random_mlp_no_bellman_pretraining')),
            'full_final_hjb_loss': fd['hjb_loss'],
            'comparator_final_hjb_loss': cd['hjb_loss'],
            'full_final_mean_hamiltonian': fd['mean_hamiltonian'],
            'claim_status': cfg['status'],
            'interpretation': cfg['read'],
        }
        if benchmark == 'inventory_service_level':
            fixed_service = row_for(metrics, benchmark, 'nbo_fixed_service_inventory')
            row['fixed_service_value'] = fixed_service[cfg['metric']]
            row['full_minus_fixed_service'] = f"{float(full[cfg['metric']]) - float(fixed_service[cfg['metric']]):.12g}"
            row['full_avg_cost'] = full['avg_cost']
            row['comparator_avg_cost'] = comp['avg_cost']
            row['full_ending_backlog'] = full['ending_backlog']
            row['comparator_ending_backlog'] = comp['ending_backlog']
        if benchmark == 'exp2_hidden_regime':
            oracle = row_for(metrics, benchmark, 'nbo_oracle_joint_action')
            row['oracle_method'] = 'nbo_oracle_joint_action'
            row['oracle_value'] = oracle[cfg['metric']]
            row['full_minus_oracle'] = f"{float(full[cfg['metric']]) - float(oracle[cfg['metric']]):.12g}"
            row['oracle_detection_accuracy'] = oracle['regime_detection_acc']
            row['full_detection_accuracy'] = full['regime_detection_acc']
            row['comparator_detection_accuracy'] = comp['regime_detection_acc']
            row['detection_accuracy_gap'] = f"{float(full['regime_detection_acc']) - float(comp['regime_detection_acc']):.12g}"
        if benchmark == 'exp3_high_dimensional_allocation':
            oracle = row_for(metrics, benchmark, 'nbo_oracle_factor')
            row['oracle_method'] = 'nbo_oracle_factor'
            row['oracle_value'] = oracle[cfg['metric']]
            row['full_minus_oracle'] = f"{float(full[cfg['metric']]) - float(oracle[cfg['metric']]):.12g}"
        out.append(row)
    path = DATA / 'nbo_full_ndu_solver_audit.csv'
    with path.open('w', newline='') as fh:
        fieldnames = list(dict.fromkeys(k for r in out for k in r.keys()))
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(out)
    print(f'wrote {path} ({len(out)} rows)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
