#!/usr/bin/env python3
"""Shared benchmark dynamics and rollout evaluators.

The current manuscript's direct solver evidence is generated by
``run_hbo_full_experiments.py`` (also exposed through
``run_source_nbo_full_experiments.py``), which trains fully trainable PyTorch-AD
actor/critic MLPs with the HBO/NBO performance/HJB-residual loss.  This module
is kept as infrastructure: it defines the benchmark specifications, rollout
evaluators, and compact action sensors used by the solver and audit scripts.

The standalone entry point below can still regenerate an older finite-horizon
Bellman diagnostic for comparison, but that diagnostic is not the headline
HBO/NBO evidence and is not listed in the active reproducibility manifest.  It
is not a CEM optimizer: policy actions are chosen by backward Bellman
maximization on each sensor grid, then evaluated out-of-sample over 30 seeds.
"""
from __future__ import annotations

import argparse
import csv
import math
import statistics as stats
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
REPRO_ROOT = SCRIPT_DIR.parent
DATA_DIR = REPRO_ROOT / 'data'
SEED_COUNT = 30
SEED_STRIDE = 1000


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -40.0, 40.0)))


def annualized_sharpe(returns, dt):
    mu = returns.mean(axis=1)
    sd = np.maximum(returns.std(axis=1), 1e-3)
    return np.sqrt(1.0 / dt) * mu / sd


def max_drawdown(paths):
    peaks = np.maximum.accumulate(paths, axis=1)
    dd = paths / np.maximum(peaks, 1e-12) - 1.0
    return dd.min(axis=1)


def seed_values(base: int) -> list[int]:
    return [base + SEED_STRIDE * (j + 1) for j in range(SEED_COUNT)]


class ValueRegressor:
    """Small tensor/random-feature trunk used for compact Bellman-image audits."""

    def __init__(self, X: np.ndarray, y: np.ndarray, *, seed: int, width: int = 64, ridge: float = 1e-5) -> None:
        self.mean = X.mean(axis=0)
        self.std = X.std(axis=0) + 1e-6
        d = X.shape[1]
        rng = np.random.default_rng(seed)
        self.W = rng.normal(0.0, 0.85, size=(d, width))
        self.b = rng.normal(0.0, 0.60, size=width)
        Phi = self.features(X)
        A = Phi.T @ Phi + ridge * np.eye(Phi.shape[1])
        rhs = Phi.T @ y
        self.coef = np.linalg.solve(A, rhs)

    @classmethod
    def constant(cls, value: float, dim: int) -> 'ValueRegressor':
        obj = cls.__new__(cls)
        obj.mean = np.zeros(dim)
        obj.std = np.ones(dim)
        obj.W = np.zeros((dim, 1))
        obj.b = np.zeros(1)
        obj.coef = np.array([value, 0.0, 0.0, 0.0])
        return obj

    def features(self, X: np.ndarray) -> np.ndarray:
        Z = (X - self.mean) / self.std
        parts = [np.ones((X.shape[0], 1)), Z, Z * Z, np.tanh(Z @ self.W + self.b)]
        return np.concatenate(parts, axis=1)

    def predict(self, X: np.ndarray) -> np.ndarray:
        return self.features(np.asarray(X, dtype=float)) @ self.coef


@dataclass
class NBOResult:
    values: list[ValueRegressor]
    state_grid: np.ndarray
    action_tables: list[np.ndarray]
    actions: np.ndarray
    residuals: list[float]
    experiment: str
    method: str
    horizon: int
    state_dim: int
    action_dim: int
    sensor_count: int
    action_count: int
    shock_count: int


@dataclass
class NBOSpec:
    experiment: str
    method: str
    horizon: int
    state_grid: np.ndarray
    actions: np.ndarray
    shocks: np.ndarray
    transition_reward: Callable[[int, np.ndarray, np.ndarray, np.ndarray], tuple[np.ndarray, np.ndarray]]
    terminal: Callable[[np.ndarray], np.ndarray]


def nearest_rows(grid: np.ndarray, X: np.ndarray) -> np.ndarray:
    scale = grid.std(axis=0) + 1e-6
    Zg = grid / scale
    Zx = X / scale
    # Chunk to avoid large temporary arrays.
    idx = np.empty(X.shape[0], dtype=int)
    for start in range(0, X.shape[0], 4096):
        chunk = Zx[start:start + 4096]
        dist = ((chunk[:, None, :] - Zg[None, :, :]) ** 2).sum(axis=2)
        idx[start:start + len(chunk)] = np.argmin(dist, axis=1)
    return idx


def solve_nbo(spec: NBOSpec, *, seed: int = 20260512, width: int = 64) -> NBOResult:
    X = spec.state_grid
    dim = X.shape[1]
    next_value = ValueRegressor.constant(0.0, dim)
    values_rev: list[ValueRegressor] = []
    action_tables_rev: list[np.ndarray] = []
    residuals_rev: list[float] = []
    # Terminal value is represented by a fitted value regressor on the same sensors.
    terminal_y = spec.terminal(X)
    next_value = ValueRegressor(X, terminal_y, seed=seed + 10_000, width=width)
    for step in range(spec.horizon - 1, -1, -1):
        q_cols = []
        for action in spec.actions:
            accum = np.zeros(X.shape[0])
            for shock in spec.shocks:
                Xn, reward = spec.transition_reward(step, X, action, shock)
                accum += reward + next_value.predict(Xn)
            q_cols.append(accum / max(1, len(spec.shocks)))
        Q = np.stack(q_cols, axis=1)
        best_idx = np.argmax(Q, axis=1)
        target = Q[np.arange(X.shape[0]), best_idx]
        fit = ValueRegressor(X, target, seed=seed + step + 137 * (1 + len(values_rev)), width=width)
        pred = fit.predict(X)
        rmse = float(np.sqrt(np.mean((pred - target) ** 2)))
        residuals_rev.append(rmse)
        action_tables_rev.append(best_idx.astype(int))
        values_rev.append(fit)
        next_value = fit
    return NBOResult(
        values=list(reversed(values_rev)),
        state_grid=X,
        action_tables=list(reversed(action_tables_rev)),
        actions=spec.actions,
        residuals=list(reversed(residuals_rev)),
        experiment=spec.experiment,
        method=spec.method,
        horizon=spec.horizon,
        state_dim=dim,
        action_dim=spec.actions.shape[1],
        sensor_count=X.shape[0],
        action_count=spec.actions.shape[0],
        shock_count=spec.shocks.shape[0],
    )


def nbo_actions(policy: NBOResult, t: int, states: np.ndarray) -> np.ndarray:
    idx = nearest_rows(policy.state_grid, states)
    aidx = policy.action_tables[min(t, policy.horizon - 1)][idx]
    return policy.actions[aidx]


# ---------------------------------------------------------------------------
# Experiment I: habit/portfolio NDU Bellman solve
# ---------------------------------------------------------------------------


def exp1_grid() -> np.ndarray:
    W = np.linspace(0.35, 1.85, 13)
    h = np.linspace(0.025, 0.24, 11)
    return np.array([[w, hh] for w in W for hh in h], dtype=float)


def exp1_actions(method: str) -> np.ndarray:
    pis = np.array([-0.60, -0.15, 0.35, 0.85, 1.20])
    cfracs = np.array([0.030, 0.060, 0.095, 0.135, 0.170])
    thetas = np.array([0.08, 0.25, 0.55, 0.85, 1.00]) if method == 'nbo_full_ndu' else np.array([0.25])
    if method == 'nbo_preference_only':
        return np.array([[0.55, 0.070, th] for th in thetas], dtype=float)
    return np.array([[pi, cf, th] for pi in pis for cf in cfracs for th in thetas], dtype=float)


def exp1_spec(method: str) -> NBOSpec:
    horizon = 40
    dt = 1.0 / horizon
    shocks = np.array([-1.5, -0.5, 0.0, 0.5, 1.5])

    def terminal(X):
        return 0.45 * np.log(np.maximum(X[:, 0], 1e-5))

    def tr(step, X, action, z):
        W = X[:, 0]
        h = X[:, 1]
        pi, cfrac, theta = action
        if method == 'nbo_preference_only':
            surplus_pressure = np.clip(h / np.maximum(W, 1e-4), 0.0, 1.0)
            pi_eff = np.clip(0.75 - 1.2 * surplus_pressure, -0.5, 1.0)
            cfrac_eff = 0.045 + 0.03 * (1.0 - surplus_pressure)
        else:
            pi_eff = pi
            cfrac_eff = cfrac
        mu = 0.11 if step < horizon // 2 else -0.05
        sigma = 0.16 if step < horizon // 2 else 0.36
        c = np.maximum(1e-5, cfrac_eff * np.maximum(W, 1e-4))
        dW = (0.02 * W + pi_eff * W * (mu - 0.02) - c) * dt + pi_eff * W * sigma * math.sqrt(dt) * z
        Wn = np.maximum(W + dW, 1e-5)
        hn = np.maximum(h + theta * (c - h) * dt, 1e-5)
        surplus = c - h
        ruined = (surplus <= 1e-4) | (Wn <= 1e-5)
        reward = ((1.0 + 0.65 * theta) * np.log(np.maximum(surplus, 1e-4))
                  - 0.10 * (theta - 0.25) ** 2
                  - 0.02 * pi_eff ** 2
                  - 0.01 * (c / np.maximum(W, 1e-4)) ** 2) * dt
        reward = np.where(ruined, reward - 2.5, reward)
        return np.stack([np.clip(Wn, 0.25, 2.05), np.clip(hn, 0.015, 0.30)], axis=1), reward

    return NBOSpec('exp1_habit_portfolio', method, horizon, exp1_grid(), exp1_actions(method), shocks.reshape(-1, 1), tr, terminal)


def eval_exp1(policy: NBOResult, seed: int, episodes: int = 256) -> dict[str, float]:
    rng = np.random.default_rng(seed)
    steps = 40
    dt = 1.0 / steps
    shock = steps // 2
    W = np.full(episodes, 1.0)
    h = np.full(episodes, 0.08)
    ruined = np.zeros(episodes, dtype=bool)
    total_reward = np.zeros(episodes)
    mean_surplus_ratio = np.zeros(episodes)
    surplus_counts = np.zeros(episodes)
    theta_paths = []
    W_paths = [W.copy()]
    h_paths = [h.copy()]
    for t in range(steps):
        action = nbo_actions(policy, t, np.stack([W, h], axis=1))
        pi, cfrac, theta = action[:, 0], action[:, 1], action[:, 2]
        if policy.method == 'nbo_preference_only':
            surplus_pressure = np.clip(h / np.maximum(W, 1e-4), 0.0, 1.0)
            pi = np.clip(0.75 - 1.2 * surplus_pressure, -0.5, 1.0)
            cfrac = 0.045 + 0.03 * (1.0 - surplus_pressure)
        mu = 0.11 if t < shock else -0.05
        sigma = 0.16 if t < shock else 0.36
        z = rng.standard_normal(episodes)
        c = np.maximum(1e-5, cfrac * np.maximum(W, 1e-4))
        dW = (0.02 * W + pi * W * (mu - 0.02) - c) * dt + pi * W * sigma * math.sqrt(dt) * z
        W_new = np.maximum(W + dW, 1e-5)
        h_new = np.maximum(h + theta * (c - h) * dt, 1e-5)
        surplus = c - h
        newly_ruined = (surplus <= 1e-4) | (W_new <= 1e-5)
        reward = ((1.0 + 0.65 * theta) * np.log(np.maximum(surplus, 1e-4))
                  - 0.10 * (theta - 0.25) ** 2
                  - 0.02 * pi ** 2
                  - 0.01 * (c / np.maximum(W, 1e-4)) ** 2) * dt
        reward = np.where(newly_ruined, reward - 2.5, reward)
        # Continue the rollout after first breach rather than zeroing future
        # rewards; this avoids making early ruin artificially attractive.
        total_reward += reward
        ruined = ruined | newly_ruined
        ratio = np.maximum(surplus, 0.0) / np.maximum(W, 1e-4)
        mean_surplus_ratio += np.where(newly_ruined, 0.0, ratio)
        surplus_counts += (~newly_ruined).astype(float)
        W = W_new
        h = h_new
        theta_paths.append(theta.copy())
        W_paths.append(W.copy())
        h_paths.append(h.copy())
    total_reward += 0.45 * np.log(np.maximum(W, 1e-5))
    theta_paths = np.stack(theta_paths, axis=1)
    W_paths = np.stack(W_paths, axis=1)
    h_paths = np.stack(h_paths, axis=1)
    surplus_ratio = mean_surplus_ratio / np.maximum(surplus_counts, 1.0)
    pre = theta_paths[:, max(0, shock - 1)]
    lag = np.full(episodes, steps - shock, dtype=float)
    for j in range(episodes):
        idx = np.where(theta_paths[j, shock:] > pre[j] + 0.10)[0]
        if idx.size:
            lag[j] = float(idx[0])
    return {
        'mean_utility': float(total_reward.mean()),
        'cew': float(np.exp(total_reward.mean()) - 1.0),
        'ruin_prob': float(ruined.mean()),
        'surplus_ratio': float(surplus_ratio.mean()),
        'adaptation_lag': float(lag.mean() / steps),
        'wealth_terminal': float(W.mean()),
        'theta_std': float(theta_paths.std()),
    }


# ---------------------------------------------------------------------------
# Experiment II: hidden-regime control
# ---------------------------------------------------------------------------


def exp2_grid(oracle: bool = False) -> np.ndarray:
    X = np.linspace(0.55, 1.65, 7)
    belief = np.array([0.08, 0.30, 0.55, 0.80, 0.95])
    prev_ret = np.array([-0.08, 0.0, 0.08])
    signal = np.array([-0.75, 0.25, 1.25])
    return np.array([[x, b, r, s] for x in X for b in belief for r in prev_ret for s in signal], dtype=float)


def exp2_actions(method: str) -> np.ndarray:
    pis = np.array([0.0, 0.25, 0.55, 0.90, 1.15])
    bnext = np.array([0.08, 0.30, 0.55, 0.80, 0.95])
    thetas = np.array([0.08, 0.25, 0.55, 0.85, 1.00]) if method == 'nbo_full_ndu' else np.array([0.25])
    return np.array([[pi, th, bn] for pi in pis for th in thetas for bn in bnext], dtype=float)


def exp2_spec(method: str) -> NBOSpec:
    horizon = 48
    dt = 1.0 / horizon
    # shock columns: regime_threshold, return_z, signal_z
    shocks = np.array([[u, rz, sz] for u in (0.20, 0.50, 0.80) for rz in (-1.0, 0.0, 1.0) for sz in (-1.0, 1.0)], dtype=float)

    def terminal(X):
        return np.zeros(X.shape[0])

    def tr(step, X, action, shock):
        wealth, belief, prev_ret, signal = X[:, 0], X[:, 1], X[:, 2], X[:, 3]
        pi, theta, bnext = action
        u, rz, sz = shock
        p_high = belief * (0.94 if step >= horizon // 2 else 0.90) + (1.0 - belief) * (0.72 if step >= horizon // 2 else 0.08)
        high = (u < p_high).astype(float)
        sigma = np.where(high > 0.5, 0.58, 0.18)
        mu = np.where(high > 0.5, -0.04, 0.10)
        ret = (0.01 + pi * (mu - 0.01)) * dt + pi * sigma * math.sqrt(dt) * rz
        Wn = np.maximum(wealth * np.maximum(1.0 + ret, 1e-4), 1e-5)
        signal_next = high + 0.50 * sz
        reward = ((1.0 + 0.55 * theta) * np.log(np.maximum(1.0 + ret, 1e-6))
                  - 0.08 * (theta - 0.25) ** 2
                  - 0.01 * np.abs(pi))
        return np.stack([np.clip(Wn, 0.35, 2.0), np.clip(bnext, 0.02, 0.98) * np.ones_like(Wn), np.clip(ret, -0.20, 0.20), np.clip(signal_next, -1.0, 2.0)], axis=1), reward

    return NBOSpec('exp2_hidden_regime', method, horizon, exp2_grid(method == 'nbo_oracle'), exp2_actions(method), shocks, tr, terminal)


def eval_exp2(policy: NBOResult, seed: int, episodes: int = 256) -> dict[str, float]:
    rng = np.random.default_rng(seed)
    steps = 48
    dt = 1.0 / steps
    shock_time = steps // 2
    X = np.full(episodes, 1.0)
    regime = np.zeros(episodes, dtype=int)
    belief = np.full(episodes, 0.15)
    prev_ret = np.zeros(episodes)
    signal = np.zeros(episodes)
    wealth_paths = [X.copy()]
    belief_paths = []
    theta_paths = []
    pi_paths = []
    regime_paths = []
    port_rets = []
    for t in range(steps):
        u = rng.random(episodes)
        if t < shock_time:
            regime = np.where(regime == 1, (u < 0.92).astype(int), (u < 0.05).astype(int))
        else:
            regime = np.where(regime == 1, (u < 0.95).astype(int), (u < 0.75).astype(int))
        signal = regime + 0.50 * rng.standard_normal(episodes)
        actions = nbo_actions(policy, t, np.stack([X, belief, prev_ret, signal], axis=1))
        pi, theta, bnext = actions[:, 0], actions[:, 1], actions[:, 2]
        if policy.method == 'nbo_oracle_joint_action':
            bnext = regime.astype(float)
            theta = np.full(episodes, 0.25)
        sigma = np.where(regime == 1, 0.58, 0.18)
        mu = np.where(regime == 1, -0.04, 0.10)
        z = rng.standard_normal(episodes)
        ret = (0.01 + pi * (mu - 0.01)) * dt + pi * sigma * math.sqrt(dt) * z
        X = np.maximum(X * np.maximum(1.0 + ret, 1e-4), 1e-5)
        prev_ret = ret
        belief = bnext
        wealth_paths.append(X.copy())
        belief_paths.append(belief.copy())
        theta_paths.append(theta.copy())
        pi_paths.append(pi.copy())
        regime_paths.append(regime.copy())
        port_rets.append(ret.copy())
    wealth_paths = np.stack(wealth_paths, axis=1)
    belief_paths = np.stack(belief_paths, axis=1)
    theta_paths = np.stack(theta_paths, axis=1)
    pi_paths = np.stack(pi_paths, axis=1)
    regime_paths = np.stack(regime_paths, axis=1)
    port_rets = np.stack(port_rets, axis=1)
    utility = ((1.0 + 0.55 * theta_paths) * np.log(np.maximum(1.0 + port_rets, 1e-6))
               - 0.08 * (theta_paths - 0.25) ** 2
               - 0.01 * np.abs(pi_paths)).sum(axis=1)
    dd = max_drawdown(wealth_paths)
    sharpe = annualized_sharpe(port_rets, dt)
    pre_pi = pi_paths[:, max(0, shock_time - 1)]
    lag = np.full(episodes, steps - shock_time, dtype=float)
    for j in range(episodes):
        idx = np.where(pi_paths[j, shock_time:] < pre_pi[j] - 0.15)[0]
        if idx.size:
            lag[j] = float(idx[0])
    detect_acc = ((belief_paths > 0.5) == (regime_paths > 0)).mean(axis=1)
    return {
        'mean_utility': float(utility.mean()),
        'cew': float(np.exp(utility.mean()) - 1.0),
        'sharpe': float(sharpe.mean()),
        'max_drawdown': float(dd.mean()),
        'adaptation_lag': float(lag.mean() / steps),
        'regime_detection_acc': float(detect_acc.mean()),
        'wealth_terminal': float(X.mean()),
    }


# ---------------------------------------------------------------------------
# Experiment III: high-dimensional allocation with Bellman-solved factor policy
# ---------------------------------------------------------------------------


def exp3_grid() -> np.ndarray:
    W = np.linspace(0.65, 1.55, 6)
    belief = np.array([-0.8, -0.25, 0.25, 0.8])
    prev_signal = np.array([-1.0, 0.0, 1.0])
    signal = np.array([-1.0, 0.0, 1.0])
    return np.array([[w, b, ps, s] for w in W for b in belief for ps in prev_signal for s in signal], dtype=float)


def exp3_actions(method: str) -> np.ndarray:
    lev = np.array([-1.20, -0.45, 0.45, 1.20])
    bnext = np.array([-0.8, -0.25, 0.25, 0.8])
    theta = np.array([0.10, 0.25, 0.35, 0.65, 0.95]) if method == 'nbo_full_ndu' else np.array([0.25])
    return np.array([[l, th, bn] for l in lev for th in theta for bn in bnext], dtype=float)


def exp3_weights(action: np.ndarray, signal: np.ndarray, assets: int = 12) -> np.ndarray:
    leverage, theta, bnext = action[:, 0], action[:, 1], action[:, 2]
    alphas = np.linspace(0.04, 0.09, assets)
    betas = np.linspace(0.6, 1.6, assets)
    alpha_dev = alphas - alphas.mean()
    beta_dev = betas - betas.mean()
    mix = 0.60 * bnext + 0.40 * signal
    raw = alpha_dev[None, :] + beta_dev[None, :] * mix[:, None] + 0.55 * (theta[:, None] - 0.25) * (alpha_dev[None, :] + 0.55 * beta_dev[None, :] * signal[:, None])
    raw = raw - raw.mean(axis=1, keepdims=True)
    return leverage[:, None] * raw / (np.sum(np.abs(raw), axis=1, keepdims=True) + 1e-8)


def exp3_spec(method: str) -> NBOSpec:
    horizon = 50
    dt = 1.0 / horizon
    shocks = np.array([[fz, iz] for fz in (-1.0, 0.0, 1.0) for iz in (-1.0, 1.0)], dtype=float)
    assets = 12
    alphas = np.linspace(0.04, 0.09, assets)
    betas = np.linspace(0.6, 1.6, assets)
    idio = np.linspace(0.10, 0.22, assets)

    def terminal(X):
        return np.zeros(X.shape[0])

    def tr(step, X, action, shock):
        W, belief, prev_signal, signal = X[:, 0], X[:, 1], X[:, 2], X[:, 3]
        action_mat = np.repeat(action[None, :], X.shape[0], axis=0)
        weights = exp3_weights(action_mat, signal, assets=assets)
        theta = action[1]
        bnext = action[2]
        fz, iz = shock
        factor = 0.92 * belief + 0.18 * fz
        eps = iz * np.ones((X.shape[0], assets))
        asset_rets = alphas[None, :] * dt + betas[None, :] * factor[:, None] * dt + idio[None, :] * math.sqrt(dt) * eps
        turnover = np.sum(np.abs(weights), axis=1)
        port_ret = np.sum(weights * asset_rets, axis=1) - 0.0025 * turnover
        Wn = np.maximum(W * np.maximum(1.0 + port_ret, 1e-4), 1e-5)
        signal_next = 0.4 * signal + factor + 0.25 * iz
        reward = ((1.0 + 0.40 * theta) * np.log(np.maximum(1.0 + port_ret, 1e-6))
                  - 0.07 * (theta - 0.25) ** 2
                  - 0.0015 * turnover)
        return np.stack([np.clip(Wn, 0.35, 2.2), np.clip(bnext, -1.2, 1.2) * np.ones_like(Wn), np.clip(signal, -1.5, 1.5), np.clip(signal_next, -1.5, 1.5)], axis=1), reward

    return NBOSpec('exp3_high_dimensional_allocation', method, horizon, exp3_grid(), exp3_actions(method), shocks, tr, terminal)


def eval_exp3(policy: NBOResult, seed: int, episodes: int = 256, assets: int = 12) -> dict[str, float]:
    rng = np.random.default_rng(seed)
    steps = 50
    dt = 1.0 / steps
    alphas = np.linspace(0.04, 0.09, assets)
    betas = np.linspace(0.6, 1.6, assets)
    idio = np.linspace(0.10, 0.22, assets)
    W = np.full(episodes, 1.0)
    belief = np.zeros(episodes)
    factor = np.zeros(episodes)
    prev_signal = np.zeros(episodes)
    prev_w = np.zeros((episodes, assets))
    wealth_paths = [W.copy()]
    theta_paths = []
    turnover_paths = []
    port_rets = []
    for t in range(steps):
        factor = 0.92 * factor + 0.18 * rng.standard_normal(episodes)
        signal = prev_signal * 0.4 + factor + 0.25 * rng.standard_normal(episodes)
        actions = nbo_actions(policy, t, np.stack([W, belief, prev_signal, signal], axis=1))
        if policy.method == 'nbo_oracle_factor':
            actions[:, 2] = factor
            actions[:, 1] = 0.25
        weights = exp3_weights(actions, signal, assets=assets)
        theta = actions[:, 1]
        eps = rng.standard_normal((episodes, assets))
        asset_rets = alphas[None, :] * dt + betas[None, :] * factor[:, None] * dt + idio[None, :] * math.sqrt(dt) * eps
        turnover = np.sum(np.abs(weights - prev_w), axis=1)
        port_ret = np.sum(weights * asset_rets, axis=1) - 0.0025 * turnover
        W = np.maximum(W * np.maximum(1.0 + port_ret, 1e-4), 1e-5)
        prev_w = weights
        prev_signal = signal
        belief = actions[:, 2]
        wealth_paths.append(W.copy())
        theta_paths.append(theta.copy())
        turnover_paths.append(turnover.copy())
        port_rets.append(port_ret.copy())
    wealth_paths = np.stack(wealth_paths, axis=1)
    theta_paths = np.stack(theta_paths, axis=1)
    turnover_paths = np.stack(turnover_paths, axis=1)
    port_rets = np.stack(port_rets, axis=1)
    utility = ((1.0 + 0.40 * theta_paths) * np.log(np.maximum(1.0 + port_rets, 1e-6))
               - 0.07 * (theta_paths - 0.25) ** 2
               - 0.0015 * turnover_paths).sum(axis=1)
    return {
        'mean_utility': float(utility.mean()),
        'cew': float(np.exp(utility.mean()) - 1.0),
        'sharpe': float(annualized_sharpe(port_rets, dt).mean()),
        'max_drawdown': float(max_drawdown(wealth_paths).mean()),
        'turnover': float(turnover_paths.mean()),
        'theta_stability': float(theta_paths.std()),
        'wealth_terminal': float(W.mean()),
    }


# ---------------------------------------------------------------------------
# Inventory service-level benchmark
# ---------------------------------------------------------------------------


def inv_grid() -> np.ndarray:
    inv = np.array([0.0, 12.0, 26.0, 42.0, 65.0])
    backlog = np.array([0.0, 8.0, 20.0, 36.0])
    ewma = np.array([14.0, 22.0, 32.0])
    last = np.array([14.0, 22.0, 34.0])
    return np.array([[i, b, e, l] for i in inv for b in backlog for e in ewma for l in last], dtype=float)


def inv_actions(method: str) -> np.ndarray:
    order_to = np.array([14.0, 24.0, 36.0, 52.0, 72.0, 96.0])
    theta = np.array([0.60, 1.00, 1.55, 2.20]) if method == 'nbo_full_ndu_inventory' else np.array([1.00])
    return np.array([[s, th] for s in order_to for th in theta], dtype=float)


def inv_spec(method: str) -> NBOSpec:
    horizon = 40
    shocks = np.array([[u, dz] for u in (0.15, 0.50, 0.85) for dz in (-1.0, 0.0, 1.0)], dtype=float)

    def terminal(X):
        inv, backlog = X[:, 0], X[:, 1]
        return -0.15 * inv - 2.0 * backlog

    def tr(step, X, action, shock):
        inventory, backlog, ewma, last_demand = X[:, 0], X[:, 1], X[:, 2], X[:, 3]
        order_up_to, theta = action
        if method == 'nbo_fixed_service_inventory':
            order_up_to = 36.0
            theta = 1.0
        q = np.maximum(0.0, order_up_to + 0.35 * backlog - inventory)
        inventory2 = inventory + q
        u, dz = shock
        p_high = 0.12 + 0.35 * sigmoid((last_demand - ewma) / 5.0)
        high = (u < p_high).astype(float)
        seasonal = 2.5 * math.sin(2.0 * math.pi * step / 20.0)
        mean = 18.0 + seasonal + high * 10.0
        sd = 3.0 + high * 1.5
        demand = np.maximum(0.0, np.rint(mean + sd * dz)).astype(float)
        need = backlog + demand
        filled = np.minimum(inventory2, need)
        invn = inventory2 - filled
        bkn = need - filled
        fill = np.where(need <= 1e-9, 1.0, filled / need)
        holding_cost = 0.28 * invn
        shortage_cost = 2.85 * bkn
        order_cost = 0.055 * q + 0.010 * np.maximum(0.0, q - 35.0) ** 2 / 35.0
        theta_cost = 0.045 * (theta - 1.0) ** 2
        cost = holding_cost + shortage_cost + order_cost + theta_cost
        reward = -cost + 8.0 * theta * (fill - 0.92) - 0.03 * theta * (fill < 0.92)
        ewmn = 0.82 * ewma + 0.18 * demand
        return np.stack([np.clip(invn, 0.0, 115.0), np.clip(bkn, 0.0, 80.0), np.clip(ewmn, 5.0, 50.0), np.clip(demand, 0.0, 60.0)], axis=1), reward

    return NBOSpec('inventory_service_level', method, horizon, inv_grid(), inv_actions(method), shocks, tr, terminal)


def eval_inventory(policy: NBOResult, seed: int, episodes: int = 512) -> dict[str, float]:
    rng = np.random.default_rng(seed)
    H = 40
    inventory = np.full(episodes, 26.0)
    backlog = np.zeros(episodes)
    ewma = np.full(episodes, 22.0)
    last_demand = np.full(episodes, 22.0)
    high = np.zeros(episodes, dtype=bool)
    total_cost = np.zeros(episodes)
    total_cost_no_theta = np.zeros(episodes)
    total_demand = np.zeros(episodes)
    total_filled = np.zeros(episodes)
    total_order = np.zeros(episodes)
    total_inventory = np.zeros(episodes)
    service_breach = np.zeros(episodes)
    total_reward = np.zeros(episodes)
    theta_path = []
    for t in range(H):
        action = nbo_actions(policy, t, np.stack([inventory, backlog, ewma, last_demand], axis=1))
        order_to, theta = action[:, 0], action[:, 1]
        if policy.method == 'nbo_fixed_service_inventory':
            order_to = np.full(episodes, 36.0)
            theta = np.ones(episodes)
        q = np.maximum(0.0, order_to + 0.35 * backlog - inventory)
        inventory = inventory + q
        flips_down = rng.random(episodes) < 0.08
        flips_up = rng.random(episodes) < 0.12
        high = np.where(high, ~flips_down, flips_up)
        seasonal = 2.5 * math.sin(2.0 * math.pi * t / 20.0)
        mean = 18.0 + seasonal + high.astype(float) * 10.0
        sd = 3.0 + high.astype(float) * 1.5
        demand = np.maximum(0.0, np.rint(rng.normal(mean, sd))).astype(float)
        need = backlog + demand
        filled = np.minimum(inventory, need)
        inventory = inventory - filled
        backlog = need - filled
        fill_rate_t = np.where(need <= 1e-9, 1.0, filled / need)
        service_breach += fill_rate_t < 0.92
        holding_cost = 0.28 * inventory
        shortage_cost = 2.85 * backlog
        order_cost = 0.055 * q + 0.010 * np.maximum(0.0, q - 35.0) ** 2 / 35.0
        theta_cost = 0.045 * (theta - 1.0) ** 2
        cost = holding_cost + shortage_cost + order_cost + theta_cost
        total_cost += cost
        total_cost_no_theta += holding_cost + shortage_cost + order_cost
        total_reward += -cost + 8.0 * theta * (fill_rate_t - 0.92) - 0.03 * theta * (fill_rate_t < 0.92)
        total_demand += demand
        total_filled += filled
        total_order += q
        total_inventory += inventory
        theta_path.append(theta)
        ewma = 0.82 * ewma + 0.18 * demand
        last_demand = demand
    fill_rate = total_filled / np.maximum(total_demand, 1.0)
    avg_cost = total_cost / H
    avg_cost_no_theta = total_cost_no_theta / H
    avg_inventory = total_inventory / H
    avg_order = total_order / H
    theta_stack = np.vstack(theta_path)
    welfare = total_reward / H
    return {
        'mean_welfare': float(np.mean(welfare)),
        'avg_cost': float(np.mean(avg_cost)),
        'avg_cost_no_theta': float(np.mean(avg_cost_no_theta)),
        'fill_rate': float(np.mean(fill_rate)),
        'ending_backlog': float(np.mean(backlog)),
        'avg_inventory': float(np.mean(avg_inventory)),
        'avg_order': float(np.mean(avg_order)),
        'theta_std': float(np.mean(np.std(theta_stack, axis=0))),
        'service_breach_count': float(np.mean(service_breach)),
    }


def solve_all(width: int = 32) -> list[NBOResult]:
    specs = []
    for method in ['nbo_full_ndu', 'nbo_fixed_pref', 'nbo_preference_only']:
        specs.append(exp1_spec(method))
    for method in ['nbo_full_ndu', 'nbo_fixed_pref_recurrent', 'nbo_oracle_joint_action']:
        specs.append(exp2_spec(method))
    for method in ['nbo_full_ndu', 'nbo_fixed_pref_joint', 'nbo_oracle_factor']:
        specs.append(exp3_spec(method))
    for method in ['nbo_full_ndu_inventory', 'nbo_action_only_inventory', 'nbo_fixed_service_inventory']:
        specs.append(inv_spec(method))
    policies = []
    for i, spec in enumerate(specs):
        print(f'[nbo] solving {spec.experiment}/{spec.method}: sensors={len(spec.state_grid)} actions={len(spec.actions)} horizon={spec.horizon}', flush=True)
        t0 = time.time()
        pol = solve_nbo(spec, seed=20260512 + 1000 * i, width=width)
        print(f'[nbo] solved {spec.experiment}/{spec.method} residual_mean={np.mean(pol.residuals):.6g} elapsed={time.time()-t0:.1f}s', flush=True)
        policies.append(pol)
    return policies


def eval_policy(policy: NBOResult, seed: int) -> dict[str, float]:
    if policy.experiment == 'exp1_habit_portfolio':
        return eval_exp1(policy, seed)
    if policy.experiment == 'exp2_hidden_regime':
        return eval_exp2(policy, seed)
    if policy.experiment == 'exp3_high_dimensional_allocation':
        return eval_exp3(policy, seed)
    if policy.experiment == 'inventory_service_level':
        return eval_inventory(policy, seed)
    raise ValueError(policy.experiment)


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open('w', newline='') as fh:
        writer = csv.DictWriter(fh, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def summarize(rows: list[dict]) -> list[dict]:
    groups = sorted({(r['experiment'], r['method']) for r in rows})
    metric_keys = sorted({k for r in rows for k in r if k not in {'experiment', 'method', 'seed', 'seed_index', 'nbo_state_dim', 'nbo_action_dim', 'nbo_sensor_count', 'nbo_action_count', 'nbo_horizon', 'nbo_shock_count', 'nbo_residual_mean', 'nbo_residual_max'}})
    out = []
    for exp, method in groups:
        rs = [r for r in rows if r['experiment'] == exp and r['method'] == method]
        row = {
            'experiment': exp,
            'method': method,
            'seed_count': len(rs),
            'nbo_state_dim': rs[0]['nbo_state_dim'],
            'nbo_action_dim': rs[0]['nbo_action_dim'],
            'nbo_sensor_count': rs[0]['nbo_sensor_count'],
            'nbo_action_count': rs[0]['nbo_action_count'],
            'nbo_horizon': rs[0]['nbo_horizon'],
            'nbo_shock_count': rs[0]['nbo_shock_count'],
            'nbo_residual_mean': rs[0]['nbo_residual_mean'],
            'nbo_residual_max': rs[0]['nbo_residual_max'],
        }
        for key in metric_keys:
            vals = [float(r[key]) for r in rs if key in r and r[key] != '']
            if not vals:
                continue
            mean = sum(vals) / len(vals)
            ci = 1.96 * (stats.stdev(vals) / math.sqrt(len(vals))) if len(vals) > 1 else 0.0
            row[key] = mean
            row[f'{key}_ci95'] = ci
        out.append(row)
    return out


def residual_rows(policies: list[NBOResult]) -> list[dict]:
    out = []
    for pol in policies:
        out.append({
            'experiment': pol.experiment,
            'method': pol.method,
            'nbo_state_dim': pol.state_dim,
            'nbo_action_dim': pol.action_dim,
            'nbo_sensor_count': pol.sensor_count,
            'nbo_action_count': pol.action_count,
            'nbo_horizon': pol.horizon,
            'nbo_shock_count': pol.shock_count,
            'mean_bellman_fit_rmse': float(np.mean(pol.residuals)),
            'max_bellman_fit_rmse': float(np.max(pol.residuals)),
            'final_step_bellman_fit_rmse': float(pol.residuals[-1]),
            'algorithm': 'nbo_style_fitted_bellman_recursion_numpy',
        })
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--outdir', default=str(DATA_DIR))
    parser.add_argument('--seeds', type=int, default=SEED_COUNT)
    parser.add_argument('--width', type=int, default=32)
    args = parser.parse_args()
    outdir = Path(args.outdir).resolve()
    t0 = time.time()
    policies = solve_all(width=args.width)
    seed_bases = {
        'exp1_habit_portfolio': 701,
        'exp2_hidden_regime': 1701,
        'exp3_high_dimensional_allocation': 2701,
        'inventory_service_level': 3701,
    }
    rows = []
    for pol in policies:
        for seed_index, seed in enumerate(seed_values(seed_bases[pol.experiment])[:args.seeds], start=1):
            metrics = eval_policy(pol, seed + 500000)
            row = {
                'experiment': pol.experiment,
                'method': pol.method,
                'seed_index': seed_index,
                'seed': seed,
                'nbo_state_dim': pol.state_dim,
                'nbo_action_dim': pol.action_dim,
                'nbo_sensor_count': pol.sensor_count,
                'nbo_action_count': pol.action_count,
                'nbo_horizon': pol.horizon,
                'nbo_shock_count': pol.shock_count,
                'nbo_residual_mean': float(np.mean(pol.residuals)),
                'nbo_residual_max': float(np.max(pol.residuals)),
            }
            row.update(metrics)
            rows.append(row)
        print(f'[nbo] evaluated {pol.experiment}/{pol.method}', flush=True)
    summary = summarize(rows)
    residual = residual_rows(policies)
    write_csv(outdir / 'nbo_full_ndu_seed_metrics.csv', rows)
    write_csv(outdir / 'nbo_full_ndu_metrics.csv', summary)
    write_csv(outdir / 'nbo_full_ndu_residual_audit.csv', residual)
    print('[nbo] summary headline:')
    for r in summary:
        if r['method'].startswith('nbo_full'):
            print(r)
    print(f'[nbo] wrote outputs to {outdir} elapsed={time.time()-t0:.1f}s')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
